feat:add button component
shubhamkumar648/growAndknow-UI pull request #4
Opened 2022-02-08 18:43 UTC by shubhamkumar648

2022-02-08 18:55 UTC, rahulcs754 reviewed
Please check change and try to use prettier to clean your code view

2022-02-08 18:55 UTC, rahulcs754 commented on styles/button.css
> +
don't leave space

2022-02-08 18:55 UTC, rahulcs754 commented on styles/button.css
> +
same as above

2022-02-08 18:55 UTC, rahulcs754 commented on styles/button.css
> +
same as above

2022-02-08 18:55 UTC, rahulcs754 commented on styles/button.css
> +
same as above

2022-02-08 18:55 UTC, rahulcs754 commented on styles/button.css
> +
use prettier and don't leave any space

2022-02-08 19:05 UTC, shuntzhere requested changes
Make sure to format the code using extensions like prettier that would remove the extra lines too, which will thus improve the readability.
Also suggested some minor changes.

2022-02-08 19:05 UTC, shuntzhere commented on component/button.html
> +          </button>
There is a typo here.

2022-02-08 19:05 UTC, shuntzhere commented on component/button.html
> +
Format this code for better readability.

2022-02-08 19:05 UTC, shuntzhere commented on component/button.html
> +        </div>
href takes a link so you can just leave a "#". No need to use #home.

2022-02-08 19:05 UTC, shuntzhere commented on styles/button.css
> +  display: flex;
You don't need to give box-sizing here.

2022-02-08 19:14 UTC, shubhamkumar648 commented on styles/button.css
> +  display: flex;
thank you forgot to remove

2022-02-08 19:16 UTC, shubhamkumar648 commented on component/button.html
> +
it will reflect  in next commit

2022-02-08 19:38 UTC, shubhamkumar648 commented
> Make sure to format the code using extensions like prettier that would remove the extra lines too, which will thus improve the readability. Also suggested some minor changes.

 yeah i used i use prettier it gives these formet

2022-02-10 04:40 UTC, rahulcs754 approved these changes

2022-02-10 12:28 UTC, shuntzhere approved these changes
Looks good now.

2022-02-10 15:16 UTC, merged